---
stages:
  - sonarqube_stage

sonarqube_ci_exemple:                                                                # au choix
  image: sonarsource/sonar-scanner-cli:${SONAR_SCANNER_CLI_VERSION}
  stage: sonarqube_stage                                                            # au choix
  variables:
    SONAR_PROJECT_BASE_DIR: "$CI_PROJECT_DIR"
  script:
    - /usr/bin/entrypoint.sh sonar-scanner -Dsonar.projectKey="$CI_PROJECT_NAME"    # sonar.projectKey defines the name of the project in SonarQube.
                                                                                    # In this example it uses the same name of the project in GitLab.
  tags:                                                                             # NOTE: this is NOT a git tag name.
    - sonarqube                                                                     # It is a GitLab tag associated in the runner section (see Step 3.
                                                                                    # Setup your project in the GÉANT deployment of GitLab)
